version: "3.2"

services:
    web:
        build: .
        ports:
            - "80:80"
        environment:
          GOOGLEMAPS_API_KEY: "insecure"
        volumes:
          - ./tourbuzz/public:/srv/web/tourbuzz/tourbuzz/public
